wazo-platform/wazo-ui

wazo_ui/plugins/provisioning/form.py
wazo_ui/plugins/provisioning/templates/wazo_engine/provisioning/config_device/edit.html
wazo_ui/plugins/provisioning/templates/wazo_engine/provisioning/config_device/list.html

reason: deprecated since 2013 (see wazo-provd-plugins commit
e0c73576649f0818bfdf4208f04aaf27330dd741)

provisioning: remove config encryption field

---

Dockerfile
debian/wazo-ui.service
etc/wazo-ui/config.yml
wazo_ui/config.py

since buster /var/run is a now a symlink to /run

use /run instead of /var/run

---

requirements.txt
wazo_ui/plugins/dird_source/view.py

reason: verify_certificate was already optional but always present. Now
the default install doesn't provide verify_certificate for wazo-auth

directories: verify_certificate is optional

---

README.md
etc/wazo-ui/config.yml
wazo_ui/config.py

use confd without ssl by default
README: add https section

Pull request for WAZO-1747-confd-http

---

wazo_ui/plugins/dird_source/form.py
wazo_ui/plugins/dird_source/static/wazo_engine/js/dird_source.js
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_conference.html
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_wazo.html
wazo_ui/plugins/dird_source/view.py

The prefix field was not handled for confd configuration in the wazo and conference dird sources.

WAZO-1807: fix prefix dird sources

---

etc/wazo-ui/config.yml
wazo_ui/config.py

use plugind without ssl by default
use webhookd without ssl by default

Pull request for WAZO-1814-plugind-without-ssl

---

etc/wazo-ui/config.yml
wazo_ui/config.py
wazo_ui/plugins/plugin/static/wazo_engine/js/plugin.js
wazo_ui/plugins/plugin/templates/wazo_engine/plugin/list.html

use same prefix name for websocketd
use provd without ssl by default

Pull request for WAZO-1820-provd-without-ssl

---

wazo_ui/plugins/dird_source/view.py

Why:
* Be consistent with wazo-dird defaults

directory: wazo: add default field for reverse lookup

---

Dockerfile
debian/wazo-ui.service
etc/wazo-ui/config.yml
wazo_ui/bin/daemon.py
wazo_ui/config.py

reason: systemd restart remove monit usage based on pid file

remove usage of PID file and use systemd options

---

.gitignore
wazo_ui/plugins/dird_source/service.py
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_conference.html
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_csv.html
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_csv_ws.html
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_google.html
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_ldap.html
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_office365.html
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_personal.html
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_phonebook.html
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_wazo.html
wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/list.html
wazo_ui/plugins/dird_source/view.py
wazo_ui/static/js/wazo-ui.js
wazo_ui/templates/macro.html

Because we want to have plugins for wazo-ui and dird_source, to intercept the url we need to know the name of the backend instead only the source uuid. We change the internal URL to /backend/source_uuid on the GET instead only /source_uuid. I added a new parameter get_url to override the default url on the double click.

use the backend name on url to get the information

---

wazo_ui/plugins/general_settings/view.py

reason: by default we query dropdown with a limit/offset, but with
pjsip, we don't care of it. So we force to remove pagination

Pull request for WAZO-1632-fix-pjsip-dropdown

---

requirements.txt

reason: flask-sqlalchgemy depends on the latest sqlalchemy version, but
the new one (1.4.0) breaks compatibility
In production, buster contains only sqlalchemy 1.2.18

freeze sqlalchemy version

---

integration_tests/suite/helpers/asset_launching_test_case.py

reason: service_port() returns only port bound to ipv4. Some host can
resolve localhost to ipv6 address and docker doesn't necessarily bind
the same port number on ipv4 and ipv6

test: use explicit ipv4 addr to connect docker

---

wazo_ui/plugins/external_auth/service.py
wazo_ui/plugins/external_auth/templates/wazo_engine/external_auth/list.html
wazo_ui/plugins/external_auth/view.py

The external auth list has been hardcoded. If you add a plugin to add a new external auth, it's impossible to configure it. Just remove the hardcoded list and rename some stuff probably from copy/paste.

Review external auth

---

wazo_ui/plugins/plugin/templates/wazo_engine/plugin/list.html
wazo_ui/user.py

why: previous refactor mixed property and session without
synchronization between them.

rollback config session usage

---

wazo_ui/plugins/extension/templates/wazo_engine/extension/list.html

Why: parking lot ID and conference ID was reversed

[WAZO-2614] extension: fix order of columns in template

---

integration_tests/suite/helpers/pages/browser.py

why: pyvirtualdisplay >=3.0 doesn't depend anymore from easyprocess

tests: remove easyprocess dependency from code

---

test-requirements.txt
wazo_ui/helpers/tests/test_classful.py
wazo_ui/helpers/tests/test_error.py
wazo_ui/helpers/tests/test_service.py
wazo_ui/helpers/tests/test_view.py
wazo_ui/plugins/call_permission/tests/test_service.py
wazo_ui/plugins/user/tests/test_service.py

why: pypi version is a backport if the python3 builtin package

test: use mock from unittest library

---

integration_tests/suite/helpers/pages/login.py
integration_tests/suite/helpers/pages/page.py
integration_tests/suite/helpers/pages/select2.py
integration_tests/suite/test_authentication.py

why: this method was removed in selenium 4.3.0

Pull request for fix-deprecated-selenium-find-element

---

wazo_ui/plugins/ha/view.py

why: self._index will trigger service.list(), which doesn't exist for HA
form. Using this fix will make the all data lost, but it's a good tradeoff
for this form (which has only 2 inputs)

ha: fix bad error handling on POST

---

debian/control

debian: remove xivo-certs dependency

---

wazo_ui/plugins/user/form.py
wazo_ui/plugins/user/templates/wazo_engine/user/edit.html
wazo_ui/plugins/user/templates/wazo_engine/user/list.html

why: this field is an unused flag (used by external project) and should not be in the UI to avoid any confusion
edit:
- old 2021 branch :sweat_smile: 
- Recent discussion: https://wazo-platform.discourse.group/t/aide-creation-utilisateur-via-api/1447/4

remove unrelated subscription type

---

wazo_ui/plugins/identity/service.py

Why:
* get_users and get_policies API endpoints were removed

tenants: fix edit form

---

wazo_ui/plugins/queue/form.py
wazo_ui/plugins/queue/templates/wazo_engine/queue/edit.html
wazo_ui/plugins/queue/templates/wazo_engine/queue/list.html

why: API does not allow to edit name after creation
why: this label is used when listing incall with destination
why: API allow to use null

Pull request for WAZO-3768-small-queue-improvement
