wazo-platform/wazo-ui

- integration_tests/assets/docker-compose.yml
- setup.py
- tox.ini
- wazo_ui/config.py
- wazo_ui/plugins/user/view.py
- wazo_ui/translations/fr_FR/LC_MESSAGES/messages.po
- wazo_ui/translations/messages.pot
- translations/fr_FR: update a few translations
- tox.ini: run compile_catalog
> make sure translation logic is working

- wazo_ui/plugins/provisioning/form.py
- wazo_ui/plugins/provisioning/plugin.py
- wazo_ui/plugins/provisioning/service.py
- wazo_ui/plugins/provisioning/templates/wazo_engine/provisioning/config_registrar/edit.html
- wazo_ui/plugins/provisioning/templates/wazo_engine/provisioning/config_registrar/list.html
- wazo_ui/plugins/provisioning/view.py
Untested on wazo-ui specifically
> WAZO-783 registrars: use confd route and update fields

- wazo_ui/plugins/conference/static/wazo_engine/js/conference.js
- wazo_ui/plugins/conference/templates/wazo_engine/conference/edit.html
- wazo_ui/plugins/conference/templates/wazo_engine/conference/list.html
- wazo_ui/plugins/group/static/wazo_engine/js/group.js
- wazo_ui/plugins/group/templates/wazo_engine/group/edit.html
- wazo_ui/plugins/group/templates/wazo_engine/group/list.html
- wazo_ui/plugins/incall/static/wazo_engine/js/incall.js
- wazo_ui/plugins/incall/templates/wazo_engine/incall/edit.html
- wazo_ui/plugins/line/templates/wazo_engine/line/edit.html
- wazo_ui/plugins/line/templates/wazo_engine/line/protocol_custom.html
- wazo_ui/plugins/line/templates/wazo_engine/line/protocol_sip.html
- wazo_ui/plugins/outcall/templates/wazo_engine/outcall/edit.html
- wazo_ui/plugins/queue/static/wazo_engine/js/queue.js
- wazo_ui/plugins/queue/templates/wazo_engine/queue/edit.html
- wazo_ui/plugins/queue/templates/wazo_engine/queue/list.html
- wazo_ui/plugins/trunk/templates/wazo_engine/trunk/edit.html
- wazo_ui/plugins/trunk/templates/wazo_engine/trunk/protocol_custom.html
- wazo_ui/plugins/trunk/templates/wazo_engine/trunk/protocol_iax.html
- wazo_ui/plugins/trunk/templates/wazo_engine/trunk/protocol_sip.html
- wazo_ui/plugins/user/static/wazo_engine/js/user.js
- wazo_ui/plugins/user/templates/wazo_engine/user/edit.html
- wazo_ui/static/js/wazo-ui.js
- wazo_ui/templates/macro.html
fix data attribute hyphenization
templates: fix data allow clear attribute
> Pull request for fix-data-attributes

- debian/control
- debian/rules
- wazo_ui/plugins/trunk/templates/wazo_engine/trunk/list.html
Depends-On: https://github.com/wazo-platform/wazo-confd/pull/41
> trunk list: display SIP trunk name instead of username

- .gitignore
- wazo_ui/plugins/general_settings/form.py
- wazo_ui/plugins/general_settings/plugin.py
- wazo_ui/plugins/general_settings/service.py
- wazo_ui/plugins/general_settings/templates/wazo_engine/general_settings/pjsip_global.html
- wazo_ui/plugins/general_settings/view.py
Depends-On: https://github.com/wazo-platform/wazo-ui/pull/29
> Wazo 1585 pjsip global

- wazo_ui/plugins/group/form.py
- wazo_ui/plugins/group/templates/wazo_engine/group/edit.html
- wazo_ui/plugins/queue/form.py
- wazo_ui/plugins/queue/templates/wazo_engine/queue/edit.html
Depends-On: https://github.com/wazo-platform/wazo-confd/pull/73
> Add mark calls answered elsewhere when cancelled to groups and queues

- wazo_ui/plugins/general_settings/form.py
- wazo_ui/plugins/general_settings/plugin.py
- wazo_ui/plugins/general_settings/service.py
- wazo_ui/plugins/general_settings/templates/wazo_engine/general_settings/pjsip_system.html
- wazo_ui/plugins/general_settings/view.py
Depends-On: https://github.com/wazo-platform/wazo-confd-client/pull/9
Depends-On: https://github.com/wazo-platform/wazo-confd/pull/75
> Wazo 1612 add the PJSIP system form

- etc/wazo-ui/config.yml
- integration_tests/assets/etc/wazo-ui/conf.d/default.yml
- wazo_ui/config.py
Depends-on: https://github.com/wazo-platform/xivo-test-helpers/pull/31
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1689
> use auth without ssl by default

- wazo_ui/plugins/dird_source/form.py
- wazo_ui/plugins/dird_source/static/wazo_engine/js/dird_source.js
- wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_conference.html
- wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_google.html
- wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_office365.html
- wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_wazo.html
- wazo_ui/plugins/dird_source/view.py
use form default for BooleanField
add prefix/https to directories
> Pull request for WAZO-1689-auth-http

- wazo_ui/plugins/incall/form.py
- wazo_ui/plugins/incall/service.py
- wazo_ui/plugins/incall/templates/wazo_engine/incall/edit.html
- wazo_ui/plugins/incall/view.py
Jira-Issue: https://wazo-dev.atlassian.net/browse/WAZO-1738
> incall: add greeting sound

- wazo_ui/plugins/user/view.py
> registrar is not mandatory

- wazo_ui/plugins/provisioning/form.py
- wazo_ui/plugins/provisioning/templates/wazo_engine/provisioning/configuration/edit.html
reason: rest host/port are broken and unused
> remove unused provisioning fields

- requirements.txt
Related: https://github.com/wazo-platform/wazo-python-flask-menu-packaging/pull/2
> bump flask-menu version

- wazo_ui/plugins/group/form.py
- wazo_ui/plugins/group/service.py
- wazo_ui/plugins/group/templates/wazo_engine/group/edit.html
- wazo_ui/plugins/group/view.py
We have API to add extension member on a group, but we don't have this feature on the UI.
> [WAZO-1982] Group add extensions members

- wazo_ui/plugins/sip_template/form.py
https://wiki.asterisk.org/wiki/display/AST/Asterisk+18+Configuration_res_pjsip_endpoint_identifier_ip
> pjsip: add missing identify section variable

- wazo_ui/plugins/group/service.py
- wazo_ui/plugins/group/templates/wazo_engine/group/edit.html
* associations on create
* edit group (PUT)
* breadcrumb
> use group uuid for all requests

- wazo_ui/http_server.py
- wazo_ui/plugins/authentication/view.py
- wazo_ui/plugins/identity/service.py
- wazo_ui/plugins/outcall/service.py
- wazo_ui/plugins/user/service.py
reason: default group cannot be dissociated and caused 403 error
> identity: di/associate only necessary group

- wazo_ui/plugins/group/form.py
- wazo_ui/plugins/group/templates/wazo_engine/group/edit.html
- wazo_ui/plugins/group/templates/wazo_engine/group/list.html
- wazo_ui/plugins/group/view.py
Depends-On: https://github.com/wazo-platform/wazo-confd/pull/193
> group: add the label field

- wazo_ui/plugins/trunk/view.py
When we create IAX or custom trunk, the form create a sip trunk by default.
> [WAZO-2396] Fix IAX trunks

- wazo_ui/plugins/plugin/templates/wazo_engine/plugin/list.html
- wazo_ui/plugins/plugin/templates/wazo_engine/plugin/list_plugins.html
- wazo_ui/static/css/wazo-ui.css
split of https://github.com/wazo-platform/wazo-ui/pull/110
> plugin: improve plugin box style

- wazo_ui/plugins/user/service.py
> WAZO-2887 Remove ignore fields from user creation

- integration_tests/suite/helpers/pages/browser.py
why: it doesn't work with latest selenium version
> test: do not use deprecated method

- wazo_ui/plugins/extension/form.py
Depends-On: https://github.com/wazo-platform/wazo-confd/pull/410
> Use uuid instead of id for the features extensions

- wazo_ui/helpers/classful.py
- wazo_ui/plugins/phonebook/form.py
- wazo_ui/plugins/phonebook/plugin.py
- wazo_ui/plugins/phonebook/service.py
- wazo_ui/plugins/phonebook/static/wazo_engine/js/phonebook.js
- wazo_ui/plugins/phonebook/templates/wazo_engine/phonebook/edit.html
- wazo_ui/plugins/phonebook/templates/wazo_engine/phonebook/edit_contact.html
- wazo_ui/plugins/phonebook/templates/wazo_engine/phonebook/list.html
- wazo_ui/plugins/phonebook/templates/wazo_engine/phonebook/manage_phonebook.html
- wazo_ui/plugins/phonebook/view.py
https://wazo-dev.atlassian.net/browse/WAZO-3356
> Wazo 3356 cannot edit contact

- wazo_ui/plugins/phonebook/form.py
- wazo_ui/plugins/phonebook/service.py
- wazo_ui/plugins/phonebook/static/wazo_engine/js/phonebook.js
- wazo_ui/plugins/phonebook/templates/wazo_engine/phonebook/edit.html
- wazo_ui/plugins/phonebook/templates/wazo_engine/phonebook/list.html
- wazo_ui/plugins/phonebook/templates/wazo_engine/phonebook/manage_phonebook.html
- wazo_ui/plugins/phonebook/view.py
depends-on: https://github.com/wazo-platform/wazo-dird-client/pull/24
> Updated phonebook plugin to new API

- wazo_ui/plugins/dird_source/form.py
- wazo_ui/plugins/dird_source/service.py
- wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_phonebook.html
- wazo_ui/plugins/dird_source/view.py
- wazo_ui/plugins/phonebook/plugin.py
- wazo_ui/plugins/phonebook/service.py
- wazo_ui/plugins/phonebook/templates/wazo_engine/phonebook/list.html
- wazo_ui/plugins/phonebook/view.py
> Pull request for configure-phonebook-source

- wazo_ui/plugins/dird_source/form.py
- wazo_ui/plugins/dird_source/service.py
- wazo_ui/plugins/dird_source/templates/wazo_engine/dird_source/form/form_phonebook.html
- wazo_ui/plugins/dird_source/view.py
https://wazo-dev.atlassian.net/browse/WAZO-3416
> WAZO-3416 render phonebook name from source

- wazo_ui/plugins/authentication/form.py
- wazo_ui/translations/fr/LC_MESSAGES/messages.po
- wazo_ui/translations/messages.pot
Depends-On: https://github.com/wazo-platform/wazo-auth/pull/345
> WAZO-3787: handle 429 error

- wazo_ui/http_server.py
> HTTP server: apply cheroot patch

- wazo_ui/plugins/trunk/form.py
- wazo_ui/plugins/trunk/templates/wazo_engine/trunk/edit.html
- wazo_ui/plugins/trunk/templates/wazo_engine/trunk/protocol_sip.html
Add new trunk field `outgoing_caller_id_format`
> [WAZO-3947] add outgoing_caller_id_format

- setup.py
- wazo_ui/config.py
- wazo_ui/plugins/outcall/view.py
- wazo_ui/plugins/phone_number/form.py
- wazo_ui/plugins/phone_number/plugin.py
- wazo_ui/plugins/phone_number/service.py
- wazo_ui/plugins/phone_number/static/wazo_engine/js/phone_number.js
- wazo_ui/plugins/phone_number/templates/wazo_engine/phone_number/edit.html
- wazo_ui/plugins/phone_number/templates/wazo_engine/phone_number/list.html
- wazo_ui/plugins/phone_number/view.py
Depends-On: https://github.com/wazo-platform/wazo-confd-client/pull/49
> Wazo 3936 phonenumber interface

- wazo_ui/plugins/phone_number/templates/wazo_engine/phone_number/list.html
firefox gets new items mixed without this line
> phonenumber: add the add to the list tpl

- wazo_ui/plugins/identity/service.py
> identity: add missing parameters to list tenants
